version: 2
jobs:
    build:
        working_director: ~/testCircle1
        docker:
            - image: circleci/python:3.4
        steps:
            - checkout
            - run:
                name: test run itself
                command: |
                    echo $API_TOKEN
            - run:
                name: test mobi_backend_qa
                command: |
                    curl -X POST --header "Content-Type: application/json" https://circleci.com/api/v1.1/project/github/BTCChina/mobi-backend-qa/tree/develop?circle-token=$API_TOKEN
