version: 2
jobs:
    build:
        working_director: ~/testCircle1
        docker:
            - image: circleci/python:3.4
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"
            - run:
                name: create ansible host
                command: |
                    sudo mkdir /etc/ansible/
                    echo "172.18.10.110" > /etc/ansible/hosts

            - run:
                name: ansible test
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    ansible-playbook api.yml
            - run:
                name: test run itself
                command: |
                    echo $API_TOKEN
                    #- run:
                # name: test mobi_backend_qa
                # command: |
                #   curl -X POST --header "Content-Type: application/json" https://circleci.com/api/v1.1/project/github/BTCChina/mobi-backend-qa/tree/develop?circle-token=$API_TOKEN
