version: 2
jobs:
    build:
        working_director: ~/testCircle1
        docker:
            - image: circleci/python:3.4
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"

            deployment:
                staging:
                    branch: master
                    codedeploy:
                    appname-DemoApplication:
                        application_root: /
                        region: us-east-2
                        # revision_location:
                        #     revision_type: S3
                        # s3_location:
                        #     bucket: my-bucket
                        #     key_pattern: appname-1234-{BRANCH}-{SHORT_COMMIT}
                        deployment_group: DemoApplication
            - run:
                name: test run itself
                command: |
                    echo success
                    #- run:
                # name: test mobi_backend_qa
                # command: |
                #   curl -X POST --header "Content-Type: application/json" https://circleci.com/api/v1.1/project/github/BTCChina/mobi-backend-qa/tree/develop?circle-token=$API_TOKEN
